### ISSUE TITLE
encoding support?

### ISSUE THREAD

**Issue by moonso** [slowkow/pytabix#3]
Hi,

thank you for this! Finally we could drop pysam.
I wounder if there is any support for specifying encoding when opening files with pytabix, like ```tabix.open(file=infile,encoding='utf-8')```?

**Comment by slowkow** [comment]
@moonso I apologize for the delayed response. Have you tried using a UTF8 file? Does it work? Is there an error message? If it fails, could you provide an example file so we can add a test case?

**Comment by moonso** [comment]
You are right, why fix something that os not broken?
I'll get back if there are any problem
